#-----------------------------------------------------------------------
#
#  DirectoryBrowserWindow : default colours for 'light' colour scheme
#
#  A colour value may have 1, 2, 3 or 4 components:
#    1 : <grey>
#    2 : <grey>, <opacity>
#    3 : <red>, <green>, <blue>
#    4 : <red>, <green>, <blue>, <opacity>
#  where
#    <grey>, <red>, <green>, <blue> are integers in the interval [0, 255]
#    <opacity> is a floating-point number in the interval [0, 1]
#
#-----------------------------------------------------------------------

controlDialog.crossIcon = 160, 80, 80

controlDialog.closeLabel.background = 236
controlDialog.closeLabel.background.hovered = 224
controlDialog.closeLabel.border = 192

controlDialog.mainPane.background = 240, 244, 248
controlDialog.mainPane.border = 112, 160, 216

nameLabel.background = 216, 232, 224
nameLabel.background.selected = 252, 224, 128
nameLabel.border = 192, 208, 200
nameLabel.border.selected = 224, 192, 96
nameLabel.text = 0

numSelectedLabel.background = 252, 248, 232
numSelectedLabel.border = 224, 208, 176
numSelectedLabel.text = 0

placeholder.text = 176, 64, 32

#-----------------------------------------------------------------------
