#-----------------------------------------------------------------------
#
#  PuzzlePane : default colours for 'light' colour scheme
#
#  A colour value may have 1, 2, 3 or 4 components:
#    1 : <grey>
#    2 : <grey>, <opacity>
#    3 : <red>, <green>, <blue>
#    4 : <red>, <green>, <blue>, <opacity>
#  where
#    <grey>, <red>, <green>, <blue> are integers in the interval [0, 255]
#    <opacity> is a floating-point number in the interval [0, 1]
#
#-----------------------------------------------------------------------

background = 252, 252, 246
background.highlighted = 192, 216, 248
background.selected = 224, 224, 220
background.selected.focused = 248, 224, 128

grid = 208
grid.focused = 152, 152, 168

symmetryLine = 200, 176, 200
symmetryLine.focused = 160, 0, 160

text = 0, 48, 160
text.editable = 0

valueSelector.background = 244, 248, 252
valueSelector.background.disabled = 230
valueSelector.background.highlighted = 200, 240, 176
valueSelector.border = 160, 136, 192
valueSelector.grid = 208
valueSelector.text = 0, 0, 160
valueSelector.text.disabled = 200

clearCellIcon.background = 64
clearCellIcon.foreground = 255

#-----------------------------------------------------------------------
