#-----------------------------------------------------------------------
#
#  SudokuGeneratorApp : default colours for 'light' colour scheme
#
#  A colour value may have 1, 2, 3 or 4 components:
#    1 : <grey>
#    2 : <grey>, <opacity>
#    3 : <red>, <green>, <blue>
#    4 : <red>, <green>, <blue>, <opacity>
#  where
#    <grey>, <red>, <green>, <blue> are integers in the interval [0, 255]
#    <opacity> is a floating-point number in the interval [0, 1]
#
#-----------------------------------------------------------------------

puzzleSelectionPane.background = 244, 244, 252
puzzleSelectionPane.border = 200, 208, 216
puzzleSelectionPane.clearIcon.background = 216, 0, 0
puzzleSelectionPane.clearIcon.foreground = 255

statusPane.background = 252, 252, 248
statusPane.border = 200, 208, 216

solutionButton.icon = 64
solutionButton.border = 200

#-----------------------------------------------------------------------
