#-----------------------------------------------------------------------
#
#  TemplateDialog : default colours for 'light' colour scheme
#
#  A colour value may have 1, 2, 3 or 4 components:
#    1 : <grey>
#    2 : <grey>, <opacity>
#    3 : <red>, <green>, <blue>
#    4 : <red>, <green>, <blue>, <opacity>
#  where
#    <grey>, <red>, <green>, <blue> are integers in the interval [0, 255]
#    <opacity> is a floating-point number in the interval [0, 1]
#
#-----------------------------------------------------------------------

graphicButton.icon = 64
graphicButton.border = 200

clearTemplateButton.disc = 64
clearTemplateButton.cross = 255

numEntriesLabel.background = 224, 248, 240
numEntriesLabel.border = 192, 224, 216
numEntriesLabel.text = 0

#-----------------------------------------------------------------------
