#-----------------------------------------------------------------------
#
#  DirectoryBrowserWindow : default colours for 'dark' colour scheme
#
#  A colour value may have 1, 2, 3 or 4 components:
#    1 : <grey>
#    2 : <grey>, <opacity>
#    3 : <red>, <green>, <blue>
#    4 : <red>, <green>, <blue>, <opacity>
#  where
#    <grey>, <red>, <green>, <blue> are integers in the interval [0, 255]
#    <opacity> is a floating-point number in the interval [0, 1]
#
#-----------------------------------------------------------------------

controlDialog.crossIcon = 224, 80, 80

controlDialog.closeLabel.background = 56
controlDialog.closeLabel.background.hovered = 72
controlDialog.closeLabel.border = 128

controlDialog.mainPane.background = 40, 40, 48
controlDialog.mainPane.border = 224, 144, 64

nameLabel.background = 48, 72, 64
nameLabel.background.selected = 96, 40, 32
nameLabel.border = 80, 104, 96
nameLabel.border.selected = 136, 72, 64
nameLabel.text = 255

numSelectedLabel.background = 88, 72, 24
numSelectedLabel.border = 128, 112, 60
numSelectedLabel.text = 255

placeholder.text = 192, 128, 96

#-----------------------------------------------------------------------
