#-----------------------------------------------------------------------
#
#  PuzzlePane : default colours for 'dark' colour scheme
#
#  A colour value may have 1, 2, 3 or 4 components:
#    1 : <grey>
#    2 : <grey>, <opacity>
#    3 : <red>, <green>, <blue>
#    4 : <red>, <green>, <blue>, <opacity>
#  where
#    <grey>, <red>, <green>, <blue> are integers in the interval [0, 255]
#    <opacity> is a floating-point number in the interval [0, 1]
#
#-----------------------------------------------------------------------

background = 32
background.highlighted = 96, 32, 48
background.selected = 96
background.selected.focused = 0, 112, 72

grid = 112
grid.focused = 144

symmetryLine = 112, 96, 72
symmetryLine.focused = 184, 128, 64

text = 252, 232, 192
text.editable = 255

valueSelector.background = 24, 30, 36
valueSelector.background.disabled = 64
valueSelector.background.highlighted = 96, 32, 48
valueSelector.border = 200, 128, 48
valueSelector.grid = 112
valueSelector.text = 252, 232, 160
valueSelector.text.disabled = 112

clearCellIcon.background = 248
clearCellIcon.foreground = 64

#-----------------------------------------------------------------------
