#-----------------------------------------------------------------------
#
#  SymbolsPane : default colours for 'dark' colour scheme
#
#  A colour value may have 1, 2, 3 or 4 components:
#    1 : <grey>
#    2 : <grey>, <opacity>
#    3 : <red>, <green>, <blue>
#    4 : <red>, <green>, <blue>, <opacity>
#  where
#    <grey>, <red>, <green>, <blue> are integers in the interval [0, 255]
#    <opacity> is a floating-point number in the interval [0, 1]
#
#-----------------------------------------------------------------------

symbolsField.background.valid = 24, 88, 24
symbolsField.background.invalid = 88, 32, 0

symbolsField.highlight.focused = 248, 224, 64
symbolsField.highlight.text.focused = 0

symbolsField.contextMenu.background = 48

symbolCountLabel.background = 60, 72, 80
symbolCountLabel.border = 88, 112, 128

#-----------------------------------------------------------------------
